# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               Iggy
tagline:             'learn something new'
description:         'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 https://github.com/IggHub
baseurl:             ''
paginate:            5
#excerpt_separator:  <!--this-->
# About/contact
author:
  name:              Igor Irianto
  url:
  email:             letsmailiggy@gmail.com

# Custom vars
version:             1.0.1

# Gems
gems: [jekyll-paginate]

#paginate: 5
paginate_path: "page:num"

#misc
