# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               Igor Irianto
tagline:             'Rails, React, Sketch'
description:         'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 https://github.com/IggHub
baseurl:             ''
paginate:            3
excerpt_separator:  <!--this-->
# About/contact
author:
  name:              Igor Irianto
  url:
  email:             letsmailiggy@gmail.com
  image:             "/assets/images/iggy_square.jpg"

# Custom vars
version:             1.1.0

# Gems
gems:                [jekyll-paginate]

#paginate: 5
paginate_path:        "page:num"

#sass
sass:
  sass_dir:           _sass
  style:              compressed
#misc
google-analytics:     UA-83941317-1
