# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               Igor Irianto
tagline:             'Rails, React, Sketch'
description:         '"All you have to decide is what to do with the time that is given to you" <span class="pull-right">- Gandalf</span>'
url:                 https://github.com/IggHub
gh_pages_url:        https://igghub.github.io
baseurl:             ''

excerpt_separator:  <!--this-->
# About/contact
author:
  name:              Igor Irianto
  url:
  email:             igor.irianto@gmail.com
  image:             "/assets/images/iggy_square.jpg"

# Custom vars
version:             1.3.0

# Gems
gems:                [jekyll-paginate]

#paginate: 7
paginate:             7
#paginate_path:        posts/page:num
paginate_path:        "page:num"
#sass
sass:
  sass_dir:           _sass
  style:              compressed

#misc
google-analytics:     UA-83941317-1
